### PR TITLE
fix node-sass warning

### PR DESCRIPTION
**Pull request by sylvaindumont**
`warning " > karma-scss-preprocessor@3.0.0" has unmet peer dependency "node-sass@>= 3.x".`

### CODE REVIEW

**Comment by amercier** [comment]
You must install `node-sass` along with `karma-scss-preprocessor`, as described in the [installation instructions](https://github.com/amercier/karma-scss-preprocessor/blob/master/README.md#installation):

> ```bash
> npm install karma-scss-preprocessor node-sass --save-dev
> ```
> **Note:** since v2.0, node-sass is used as a peer dependency. That is why you need to install it along with this module.

**Comment by sylvaindumont** [comment]
@amercier It happens despite node-sass@4.10.0 being installed, yarn seems to have trouble with both [x-range](https://docs.npmjs.com/misc/semver#x-ranges-12x-1x-12-) and >=.
That's why the pr replace the x-range with a normal version, it has the same meaning but it is correctly understood by yarn.

**Comment by amercier** [comment]
Oh, I see. Let me have a closer look.

**Comment by amercier** [comment]
@sylvaindumont 

I could not reproduce the issue. Here are the steps I have taken:

```
❯ mkdir karma-scss-preprocessor-playground
❯ cd karma-scss-preprocessor-playground
```
```
❯ yarn init
yarn init v1.3.2
question name (karma-scss-preprocessor-playground):
question version (1.0.0):
question description:
question entry point (index.js):
question repository url:
question author:
question license (MIT):
question private:
success Saved package.json
✨  Done in 5.65s.
```
```
❯ yarn add karma-scss-preprocessor node-sass --dev
yarn add v1.3.2
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved lockfile.
success Saved 176 new dependencies.
├─ abbrev@1.1.1
├─ [...]
├─ karma-scss-preprocessor@4.0.0
├─ [...]
├─ node-sass@4.10.0
├─ [...]
└─ yargs@7.1.0
✨  Done in 11.49s.
```

No warnings triggered and resulting `package.json` file is:
```json
{
  "name": "karma-scss-preprocessor-playground",
  "version": "1.0.0",
  "main": "index.js",
  "author": "Alex Mercier <...>",
  "license": "MIT",
  "devDependencies": {
    "karma-scss-preprocessor": "^4.0.0",
    "node-sass": "^4.10.0"
  }
}
```

Yarn seems to understand correctly `>= 3.x` here. Could you provide a minimalist repository, or steps to reproduce the issue, please?

Also, could you provide your `node` and `yarn` versions, please? Mine are:
- `node v11.3.0`
- `yarn 1.3.2`

**Comment by sylvaindumont** [comment]
I can't reproduce it either with node 10.14, and various versions of yarn. Sorry for the inconvenience, I must had a weird node/yarn/deep deps combination a year ago that caused this yarn bug. Definitely not happening anymore.

**Comment by amercier** [comment]
@sylvaindumont Thanks for clarifying and closing the issue.

Anyone: feel free to re-open if you ever encounter the problem again. In such case, please provide your NodeJS and NPM/Yarn version for reproducibility.

**Pull request closed without merging**
